### ISSUE TITLE
ff-radio-group item is not shown as "selected" when page loads

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/forge-ui-components#122]
### Current Behavior

When a page with a ff-radio-group is loaded, its current selection is not rendered and the item cannot be clicked until another option is first set

Demo (on staging) _(same issue on local)_

https://user-images.githubusercontent.com/44235289/215843670-639d619e-19cb-4ade-b28b-866065dec152.mp4

View of Vue
![chrome_BmWTvbOEPJ](https://user-images.githubusercontent.com/44235289/215845717-5d7b5bf5-cbdb-4fa9-8c3f-f85061a53638.gif)

### Expected Behavior

ff-radio-group item should be shown be rendered as "selected" when its option is set

### Steps To Reproduce

* visit any template in admin -> templates
* go to the security settings
* if necessary, set an option and save (e.g. "none")
* refresh browser / navigate home
* once more visit the same template in admin -> templates
* go to the security settings

### Environment

- FlowForge version: 1.3-git, v1.3.1-f4c8c01-20230125.0 (staging)
- Node.js version: 16
- npm version:
- Platform/OS: Windows
- Browser: Chrome (latest)

**Comment by hardillb** [comment]
Verified on Staging
