### ISSUE TITLE
Toggle Switch

### ISSUE THREAD

**Issue by joepavitt** [flowforge/forge-ui-components#150]
### Description

per: https://vuetifyjs.com/en/components/switches/

multiple scenarios popping up where a toggle switch, with customisable icon state would be very beneficial. Really like the new one in Figma for enabling developer mode, which we could replicate for our own Device "Developer Mode"

<img width="96" alt="Screenshot 2023-07-11 at 17 19 22" src="https://github.com/flowforge/forge-ui-components/assets/99246719/127b5b06-f204-4c64-bd06-8cf8a9371dad">

**Comment by Steve-Mcl** [comment]
In particular, the "loading" state (to reflect an async operation is being actioned)

https://vuetifyjs.com/en/components/switches/#states
