### ISSUE TITLE
Interactive & Accessible Documentation on GitHub Pages

### ISSUE THREAD

**Issue by joepavitt** [flowforge/forge-ui-components#2]
### Epic

#1

### Description

As a: Developer

I want to: be able to read the documentation via GitHub (pages)

So that: I do not have to `git clone` the repository and run a documentation server locally.

### Acceptance Criteria

- [x] Can navigate to a relevant GitHub pages link and view the interactive documentation
- [x] Link to documentation from the README.md

**Comment by joepavitt** [comment]
Have got an `npm run build-docs` command working, which produces a static version of the documentation into `/dist/docs`.

This has been setup as a git subtree, as per guidance [here](https://learnvue.co/2020/09/how-to-deploy-your-vue-app-to-github-pages/#step-4-run-git-subtree-push-prefix-dist-origin-gh-pages). 

GitHub pages has been configured to render from the [`gh-pages` branch:](https://github.com/flowforge/flowforge-ui-components/tree/gh-pages) where the code (and `index.html`) is definitely present.

<img width="712" alt="Screenshot 2022-03-03 at 10 17 01" src="https://user-images.githubusercontent.com/99246719/156544575-ac4cf1a8-545f-4f87-8d67-f74443da1888.png">
 
But get a 404 when we visit https://flowforge.github.io/flowforge-ui-components/ and I'm not entirely sure why...

**Comment by knolleary** [comment]
https://flowforge.github.io/flowforge-ui-components/ works for me

**Comment by joepavitt** [comment]
Yeah, that's really strange. Working for me now too, turns out I just needed to be a bit more patient!

**Comment by joepavitt** [comment]
GitHub Pages link added to documentation: https://github.com/flowforge/flowforge-ui-components/commit/c7375e984c900133f936f44da1dd1ce6a5f6d203
