### ISSUE TITLE
Dialog header doesn't standout against main header

### ISSUE THREAD

**Issue by knolleary** [flowforge/forge-ui-components#21]
### Current Behavior

If the dialog overlaps with the page header, there's no visual separation/contrast between the dialog header and page header and the dialog feels lost.

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/51083/170576288-045ed385-fd44-4434-a339-739ec1ca5790.png">

**Comment by sammachin** [comment]
@joepavitt link to fix in flowforge around max height

**Comment by joepavitt** [comment]
@knolleary can you remember which PR/issue this was fixed in? I remember you added it with some other work recently, but can't track it down.

**Comment by joepavitt** [comment]
well... that's embarrasing.
