### ISSUE TITLE
Design guidance on tooltip/inline help

### ISSUE THREAD

**Issue by knolleary** [flowforge/forge-ui-components#27]
### Description

As our UI gains more features we need to think about how the user experiences it - and how we can provide them help.

For example, when editing a Template you currently get a select box to chose between 'locked' and 'editable' - without a lot of context as to what that is referring to. There is a suggestion to change that to a locked/unlocked padlock icon - which doesn't provide any additional context to the user.

When you view project settings themselves, any locked setting gets a padlock icon next to it. The icon by itself doesn't help the user understand *why* it is locked. It would be helpful to have a tooltip on the icon that provides an explanation.

It would be helpful to have a consistent strategy/design for tooltips and ways of providing inline help.

**Comment by joepavitt** [comment]
@sammachin I'd like to bring this forward as a priority, a lot of UX issues could be solved in introducing a tooltip as a short term fix. Longer term, there are more drastic changes to be made, but a tooltip should be present where possible.

**Comment by sammachin** [comment]
Makes sense, happy to add it to this iteration at least to get the capability into ui-components? we can then apply to the forge app where needed?

**Comment by joepavitt** [comment]
`ff-tooltip` now available in `forge-ui-components`: https://github.com/flowforge/forge-ui-components/pull/53

Will do a pass of FlowForge UI to implement these where appropriate.

**Comment by Pezmc** [comment]
@joepavitt Do you have a list of places to add tooltips in mind? I know we discussed adding them to the onboarding flow and terminology like stacks/templates.

**Comment by joepavitt** [comment]
Nothing formal at the moment - I was going to do a sweep of some golden path tasks, as just fill the gaps where I think they're required.

**Comment by joepavitt** [comment]
@Pezmc fyi - just tried to add a tooltip into FlowForge from ui-components and getting an error that the directive is not recognised. Will continue to dev on https://github.com/flowforge/flowforge/issues/1041 - if you get bandwidth and have a chance to try out to see what the issue would be, that'd be really helpful as I'm bogged down in CSS updates at the moment.

**Comment by Pezmc** [comment]
@joepavitt Let me know that the issue appears to be resolved, possibly due to node package issues locally.

**Comment by joepavitt** [comment]
This issue has been floating around for a while. Just to provide relevant updates:

**done:**
- `ff-tooltip` added into `forge-ui-components` for inline hover tooltips
- Info Dialogs added for pages in FlowForge UI: https://github.com/flowforge/flowforge/pull/1458

**todo:**
- sweep through forms in UI that could benefit from inline tooltips, e.g. "project type" and "stack" in create project form.

**Comment by knolleary** [comment]
We have ff-tooltip in place and info dialogs introduced. That satisfies the reqs of this story. A followon issue will be raised to add tooltips as needed.
