### ISSUE TITLE
Handle nested data-table searching

### ISSUE THREAD

**Issue by joepavitt** [flowforge/forge-ui-components#35]
### Description

With the new search functionality for a data-table, we can type any text input into the search bar, and our data-table auto-filters it's content, searching through all properties of the data bound to a given row. This is limited however, to just one layer within that data object.

So, when searching say a project name for a device, this is not currently supported as the device as has a structure like:

```
{
    "id": "<device-id",
    "name": "Device Name",
    "project": {
        "name": "Project Name"
    }
}
```

here, we're able to search `device.id`, `device.name`, but not `device.project.name`. It is possible to pass `search-fields` property to a `data-table`, but this also only supports single depth.

Changes should be made such that:

- [ ] We search all available depths of an object by default
- [ ] If a nested property is provided in the `search-fields` property (e.g. `:search-fields="['project.name']"`) we should be able to search/filter accordingly.

**Comment by Pezmc** [comment]
Verified nested search on staging (no use of deep search fields yet).
