### ISSUE TITLE
Feature: allow both `key` and `component` in a ff-data-table column definition

### ISSUE THREAD

**Issue by knolleary** [flowforge/forge-ui-components#43]
I have data of the format:
```
[
  {
    name: 'foo'
    type: {
        id: 123,
        name: 'my-type'
   }
  }
]
```

I want a table with two columns - `name` and `type`. For the `type` column, I want to use a custom component that knows how to render a `type` object.

Currently, I can set `component` in the column definition to provide the custom component, but it always gets bound to the full data item.

```
columns: [
                { label: 'Name', key: 'name' },
                { label: 'Type', component: { is: markRaw(TeamTypeCell) }, sortable: true }
]
```

Because of that, I have to define the custom component to receive the top level property name (`type`) and then access its properties to get the details of the object. But that makes the component less portable as it might not always have a top level property name of `type`.

I would like the ability to also specify `key` to bind a particular value to the component, rather than the whole thing.
```
columns: [
                { label: 'Name', key: 'name' },
                { label: 'Type', key: 'type', component: { is: markRaw(TeamTypeCell) }, sortable: true }
]
```
With that, the component can just define its properties as those of the `type` object without needing to know the top level property name.

**Comment by joepavitt** [comment]
One thing that will trip this particular proposed solution is that `key` is used for sorting. The component does currently support the use of both, but it uses `key` for sorting-only. We do also have the `map` option for the component, which enables a re-mapping of properties, but this doesn't support nested properties. It is this latter feature that we should seek to build.

**Comment by knolleary** [comment]
I'm hitting this again with the new Admin Project view I'm working on - and I'm not really clear on the preferred resolution.

I have an array of projects in the following form (simplified here)

```
[
   {
      id: "project-id",
      name: "a project",
      team: {
          id: "team-id",
          name: "name"
      }
   }
]
```

In the table, I want the first column to be the Project Name, the second column the Team Name. However, I don't want to just display the raw property - I want to use the common component we have for displaying Team Names.

The existing component expects to receive the props `id` and `name` _of the team_. With the current data table, it receives the id and name of the _project_.

As a workaround, I've added `team` as a prop of the component and updated it to use that if present: `{{ team ? team.id : id }}`.

That works visually, but now I cannot sort the table based on the team column - because it doesn't know how to sort objects, rather than more primitive types.

So the sort feature needs a way to support nested properties (eg `team.name`), whilst retaining the fact that logically the column is showing the `team` property.

**Comment by knolleary** [comment]
I have raised #51 that adds support for nested properties in both the `key` and `map` properties.

Some more thought is needed around how the filter functionality should apply here - but that can be done another time.
