### ISSUE TITLE
Users table doesn't sort on Password Expired 

### ISSUE THREAD

**Issue by sammachin** [flowforge/forge-ui-components#44]
### Current Behavior

As an admin I cannot sort the users table by the password expired column, other columns such as admin or username work.

I can change the sort setting but it has no effect on the ordering in the table

### Expected Behavior

I would expect the order to change to group all users with an expired password as true to be together.

### Steps To Reproduce

On Prod login as admin
Goto /admin/users/general
Click the sort on the password expired column.

### Environment

- FlowForge version: 0.8.0
- Node.js version: v16.16
- npm version:
- Platform/OS: Mac 12.5
- Browser: Chrome 104

**Comment by joepavitt** [comment]
Not completely closed yet, as need to push a new release of components, and then update the FloeForge `package.json` to use the latest version
