### ISSUE TITLE
Feature: Allow ff-dialog to stay open when confirm clicked

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/forge-ui-components#48]
I wish to manually control closure of the dialog so that it remains open after the `confirm` action. 
As it stands, the dialog close regardless of success

### Proposal...
* add a new `prop` called `closeOnConfirm` with a default value of `true` 
  * default ensure backwards compatible
* in the `confirm ()` method, dont call `this.close()` if `this.closeOnConfirm === false`

### Scenario (before feature)...
1. dialog asks user to enter a value
2. value is POSTed to forge
3. forge returns a 4xx error
4. dialog closes anyway - no chance of keeping dialog open (cant show toast, user loses edits etc)

### Scenario (after feature)...
1. dialog asks user to enter a value
2. value is POSTed to forge
3. forge returns a 4xx error
4. call `Alerts.emit('Invalid value')`
5. dialog remains open
6. user corrects the value
7. value is POSTed to forge
8. forge returns a 200 OK
9. user code calls `this.$refs.dialog.close()` to manually close the dialog

**Comment by sammachin** [comment]
verified in staging
