### ISSUE TITLE
Setting `:rows-selectable="true"` on `ff-data-table` breaks kebab menu

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/forge-ui-components#58]
### Current Behavior

![chrome_cV5ONeOmpT](https://user-images.githubusercontent.com/44235289/195653905-e0ea111d-5d33-4e88-8c08-f54ae9766a59.gif)

Clicking the kebab menu on a table results in the  `@row-selected` event being fired.

### Expected Behavior

Show the kebab menu and inhibit the `@row-selected` event

### Steps To Reproduce

* Add a ff-data-table with items
* Set `:rows-selectable="true" @row-selected="editRow"` 
* in method `editRow` navigate to another view (e.g. `this.$router.push({name: 'MyEditor', params: { id: row.id })`)

### Environment

- FlowForge version: 0.10.0-git
- Platform/OS: Windows
- Browser: Chrome

**Comment by Pezmc** [comment]
Verified on staging
