### ISSUE TITLE
table does not sort correctly when empty fields are present 

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/forge-ui-components#59]
### Current Behavior

![chrome_UOhS68bPmt](https://user-images.githubusercontent.com/44235289/195800523-4764f638-e71d-43bc-826a-e6f09d697328.gif)

### Expected Behavior

when sorting a column with blank fields, the blanks should be grouped together and placed at the top or bottom (depending on sort direction)

### Steps To Reproduce

- add several rows to the templates table - leave a few blank descriptions
- try sorting by description

### Environment

- FlowForge version: 0.10.0-git
- Node.js version: na
- npm version: na
- Platform/OS: windows
- Browser: chrome

**Comment by Steve-Mcl** [comment]
> could be attacked alongside #35 as both linked to the table searching

Agreed & I see Pex has picked up #35. Perhaps @Pezmc could pick this up too?

**Comment by Pezmc** [comment]
Picked up. FYI I now have a bit of a backlog assigned to me!

**Comment by Steve-Mcl** [comment]
What did you use as the empty value on your first trial? I'm guessing it was a space?

My suspicion is on the templates, the empty fields have no value or are undefined or something else. So the sorting drops out or fails under the hood and only partially sorts the data. Look at my GIF above, first two entries have text value. They seem to sort and then the sorting stops at the first blank.

**Comment by Pezmc** [comment]
@Steve-Mcl and I dug into this a bit further, and it's likely an issue to do with `null`/`undefined`/`""`, I'm going to update the logic to use `""` for any sorting given they're presented in the UI as strings.

**Comment by Steve-Mcl** [comment]
verified on staging...


![Image](https://user-images.githubusercontent.com/44235289/198085561-d1f190c4-aa04-4bc9-9f80-23e83ba7d1e2.gif)
