### ISSUE TITLE
Dropdown buttons are text selectable

### ISSUE THREAD

**Issue by Pezmc** [flowforge/forge-ui-components#83]
### Description

When hovering over any text in a dropdown, it looks like a click will start selecting text. 

<img width="318" alt="Screenshot 2022-10-24 at 16 15 00" src="https://user-images.githubusercontent.com/507155/197547833-105e2019-26dc-43ae-a250-b38690f8226f.png">

It should either:
 - Use the hover cursor
 - Disable text interaction (`user-select: none;`)

**Comment by Steve-Mcl** [comment]
related: https://github.com/flowforge/flowforge/pull/1114

**Comment by Pezmc** [comment]
Closing in favour of https://github.com/flowforge/flowforge/pull/1114
