### ISSUE TITLE
Missing component: Ticks or crosses for displaying true/false

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/forge-ui-components#9]
### Current Behavior

![Screenshot 2022-04-12 at 09 18 15](https://user-images.githubusercontent.com/2529595/162903125-84312341-09b5-4eec-95d3-5ad18701a0e0.png)

it would be nicer if that didn't read "true" or "false"

### Expected Behavior

A ui component to display these values

### Steps To Reproduce

Browse to the users list in the admin interface.

**Comment by joepavitt** [comment]
forge-ui-components is missing a lot at the moment. This is very much a /flowforge issue at the moment. Completely agree we shouldn't be showing true/false in text format like this.

**Comment by sammachin** [comment]
@joepavitt will this be resolved as part of https://github.com/flowforge/flowforge/issues/794

**Comment by joepavitt** [comment]
@sammachin it certainly will - by default now, Booleans will display as a tick. See examples in: https://flowforge.github.io/forge-ui-components/#ff-data-table

**Comment by joepavitt** [comment]
Closed in https://github.com/flowforge/forge-ui-components/pull/31
